// Per-avatar screen rectangles inside the 50×50 sprite cell.
//
// Generated by scripts/extract_avatar_screens.py — re-run that script
// after replacing renderer/public/avatar.png and paste the resulting
// array back here. The detector also has a `--debug` mode that overlays
// the rects on a 6×-scaled sprite so you can eyeball the alignment.
//
// AgentAvatar.vue uses these to position state overlays (blink, code
// flicker, etc.) precisely on top of each robot's display panel,
// independent of the rendered avatar size.

export interface AvatarScreenRect {
  /** Left edge in sprite pixels, relative to the cell. */
  x: number
  /** Top edge in sprite pixels, relative to the cell. */
  y: number
  /** Width in sprite pixels. */
  w: number
  /** Height in sprite pixels. */
  h: number
}

export const AVATAR_SCREEN_RECTS: ReadonlyArray<AvatarScreenRect> = [
  /*  0 */ { x: 11, y: 25, w: 26, h: 16 },
  /*  1 */ { x: 14, y: 25, w: 25, h: 15 },
  /*  2 */ { x: 13, y: 23, w: 24, h: 17 },
  /*  3 */ { x: 14, y: 25, w: 25, h: 16 },
  /*  4 */ { x: 14, y: 27, w: 25, h: 13 },
  /*  5 */ { x: 12, y: 24, w: 26, h: 15 },
  /*  6 */ { x: 12, y: 24, w: 26, h: 15 },
  /*  7 */ { x: 13, y: 22, w: 24, h: 16 },
  /*  8 */ { x: 11, y: 22, w: 27, h: 16 },
  /*  9 */ { x: 14, y: 25, w: 24, h: 14 },
  /* 10 */ { x: 13, y: 23, w: 23, h: 11 },
  /* 11 */ { x: 12, y: 19, w: 24, h: 13 },
  /* 12 */ { x: 13, y: 23, w: 24, h: 15 },
  /* 13 */ { x: 12, y: 19, w: 25, h: 18 },
  /* 14 */ { x: 11, y: 25, w: 21, h: 13 },
  /* 15 */ { x: 11, y: 21, w: 26, h: 17 },
  /* 16 */ { x: 12, y: 21, w: 23, h: 17 },
  /* 17 */ { x: 10, y: 23, w: 23, h: 16 },
  /* 18 */ { x: 13, y: 21, w: 25, h: 17 },
  /* 19 */ { x: 11, y: 22, w: 25, h: 17 },
] as const
